= Morloc Technical Manual
:source-highlighter: pygments
:pygments-style: emacs
:imagesdir: images
:includedir: sections
:stem: latexmath
:sectnums:
:bibtex-file: references.bib
:bibtex-style: cambridge-university-press-numeric.csl
:bibtex-order: appearance
:toc: left


[latexmath]
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
\[
\def\ea{\widehat{\alpha}}
\def\eb{\widehat{\beta}}
\def\eg{\widehat{\gamma}}
\def\sep{ \quad\quad}
\newcommand{\mark}[1]{\blacktriangleright_{#1}}
\newcommand{\expr}[3]{#1\ \ \vdash\ #2\ \dashv\ \ #3}
\newcommand{\packto}[2]{#1\ \approx >\ #2}
\newcommand{\apply}[3]{#1 \bullet #2\ \Rightarrow {\kern -1em} \Rightarrow\ #3}
\newcommand{\subtype}[2]{#1\ :\leqq\ #2}
\newcommand{\braced}[1]{\lbrace #1 \rbrace}
\]
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

== What is `morloc`?

`morloc` is a functional programming language where functions are imported from
foreign languages and unified through a common type system. The compiler
generates the code needed to compose functions across languages and also to
direct automation of mundane tasks such as data validation, type/format
conversions, data caching, distributed computing, and file reading/writing.

The ultimate purpose of the Morloc system is to serve as the foundation for a
universal library of functions. Each function in the library has a universal
type that specifies how the function relates to other functions. Each function
has zero or more implementations. Each implementation has a language-specific
type that aligns with the universal type. The Morloc compiler takes the
specification for a program, written as a composition of typed functions, and
generates an optimized program.

Morloc is a query language that takes a program specification and searches
against a function database, returning an optimized composition of functions.
The functions may be selected all from one language or from several.

== Getting Started

```
export hello
hello = "Hello world!!!"
```

include::{includedir}/examples.asc[]

// = Philosophy
// // include::{includedir}/motivation.asc[]
//
// include::{includedir}/types.asc[]

== Syntax and Features

include::{includedir}/features.asc[]

== Code Generation and Optimization

include::{includedir}/code-generation.asc[]

== Specification 

include::{includedir}/type-specification.asc[]

== In Development

include::{includedir}/refinement-types.asc[]

// the module system and environment

// // TODO: salvage the goods from this file (there is a lot of good)
// include::{includedir}/architecture.asc[]
// include::{includedir}/tech-tree.asc[]

// = The Future
//
// include::{includedir}/unsettled-issues.asc[]
//
// include::{includedir}/pieces.asc[]
//
// include::{includedir}/workflow.asc[]
//
// = Related work
//
// include::{includedir}/related-work.asc[]
//
// [glossary]
// = Glossary
//
// include::{includedir}/glossary.asc[]
//
// [appendix]
//
// = LOC (old version of Morloc)
//
// LOC was the first working(ish) version of `morloc`
//
// include::{includedir}/LOC.asc[]



[bibliography]
= References

bibliography::[]

// // flotsam
// include::{includedir}/old-letter.asc[]
//
// include::{includedir}/build-system.asc[]
//
// include::{includedir}/forms-of-data.asc[]
//
// include::{includedir}/function-roles.asc[]
//
// include::{includedir}/graph.asc[]
//
// include::{includedir}/manifolds-and-codegen.asc[]
//
// include::{includedir}/modules.asc[]
